### PR TITLE
`benchmark`->`benchmarked`, clean deps

### PR DESCRIPTION
**Pull request by tunnckoCore**
- clean devdeps
- replace `benchmark.js` with `benchmarked`
- added one new implementation
- comment the `if array` check in benchmarks

Whats your thoughts of the `tricky.js` idea? Just strict comparison last character.. lol.
Actually this is logical and loop isn't needed.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
`tricky.js` implementation is faster when string is big and slower when string is small, than `while.js`.

**Comment by tunnckoCore** [comment]
@jonschlinkert also this, haha
okey, you cold, sorry but. :)
can you share thoughts about [tricky.js](https://github.com/tunnckoCore/ends-with/blob/f6c0c730cc48ec042be21d5cdef27bf46f17a786/benchmark/implementations/tricky.js) implementation? Have logic?
Because I have this also [here](https://github.com/tunnckoCore/starts-with/blob/master/benchmark/code/tricky.js) at `starts-with`

**Comment by tunnckoCore** [comment]
I just loop over my todos. ;d

**Comment by jonschlinkert** [comment]
> can you share thoughts about tricky.js implementation? Have logic?

seems good, I think you have all the info you need based on what you said about big strings vs. small. the real question is: who is the user, and what will they use this for most often? then you will have your answer :)

try this one:

```js
return a.slice(-b.length) === b;
```
or `substr`

**Comment by jonschlinkert** [comment]
> I just loop over my todos. ;d

lol

**Comment by jonschlinkert** [comment]
> can you share thoughts about tricky.js implementation? Have logic?
> Because I have this also here at starts-with

wait, I didn't pay enough attention to this before until I pulled it down. `charAt()` only tests one character at a time. So doing `endsWith('foo.ab', '.bb')` will give a false positive. that's why it needs to be done [like this](https://github.com/jonschlinkert/ends-with/blob/master/benchmark/implementations/while.js#L15)

**Comment by tunnckoCore** [comment]
> So doing endsWith('foo.ab', '.bb') will give a false positive.

hmm, good case. 

Yea, when I think now this `tricky.js` is out of scope of this lib and is logicless, huh no need for separate lib for this, haha. wtf on me, lol

Ok, we can should remove it from benchmarks.

**Comment by jonschlinkert** [comment]
> wtf on me,

no that's ok. `.charAt()` is not used very often. It's understandable

**Comment by jonschlinkert** [comment]
I wanted to merge this and push it up earlier but the github ddos attacks were going on. I'll have to do this later or tomorrow

**Comment by tunnckoCore** [comment]
> .charAt() is not used very often. It's understandable

no, I know what it does

> github ddos attacks were going on

yeaaaa...and I think npmjs.com also :(

**Comment by jonschlinkert** [comment]
just fyi I have a bad cold. I'll get this merged in asap. and all the other prs!! thanks so much!

**Comment by tunnckoCore** [comment]
no problem ;d I also have, from yestarday.

**Pull request merged**
